name: Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-push-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract image tag
        id: vars
        run: echo "sha_short=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ DOCKERHUB_USERNAME }}/my-devops-app:${{ steps.vars.outputs.sha_short }}
            ${{ DOCKERHUB_USERNAME }}/my-devops-app:latest

      - name: Update Helm values for dev
        run: |
          sed -i 's|tag: ".*"|tag: "${{ steps.vars.outputs.sha_short }}"|' deploy/helm/my-devops-app/values-dev.yaml

      - name: Update Helm values for prod
        run: |
          sed -i 's|tag: ".*"|tag: "${{ steps.vars.outputs.sha_short }}"|' deploy/helm/my-devops-app/values-prod.yaml

      - name: Commit updated Helm values
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add deploy/helm/my-devops-app/values-dev.yaml deploy/helm/my-devops-app/values-prod.yaml
          git diff --cached --quiet || git commit -m "ci: update image tag to ${{ steps.vars.outputs.sha_short }}"

      - name: Push updated Helm values
        run: |
          git push